version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sanity
      MONGO_INITDB_ROOT_PASSWORD: wordpass
    volumes:
      - dbdata:/docker-entrypoint-initdb.d
#  provider:
#    build:
#      dockerfile:
#        provider/Dockerfile
#    ports:
#      - "50051:50051"
#      - "5001:5001"
  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    ports:
      - "50052:50052"
      - "5002:5002"
#  visualizer:
#    build:
#      dockerfile:
#        visualizer/Dockerfile
#    ports:
#      - "50053:50053"
#      - "5003:5003"
volumes:
  dbdata:
