version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sanity
      MONGO_INITDB_ROOT_PASSWORD: wordpass
    volumes:
      - dbdata:/docker-entrypoint-initdb.d
  provider:
    build:
      dockerfile:
        provider/Dockerfile
    environment:
      - CLIENT_PORT=5001
      - SERVER_PORT=50051
    ports:
      - "5001:5001"
      - "50051:50051"
volumes:
  dbdata:
